### ISSUE TITLE
Usar dotenv para gestionar variables de entorno

### ISSUE THREAD

**Issue by GryzleeVEVO** [UNIZAR-30226-2024-11/Backend#8]
Basicamente que cosas como el puerto, donde esta la BD, contraseñas, etc.. esten en un fichero .env

Esta la librería [Dotenv](https://www.npmjs.com/package/dotenv) para hacer justamente eso. Menos variables hardcodeadas.

**Comment by isma-3788** [comment]
A parte de utilizar dotenv para esto, utilizamos [dotenv-vault](https://github.com/dotenv-org/dotenv-vault) para hacerlo de manera segura? Es como otro github. Requiere hacer doble pull y doble push. @GryzleeVEVO

**Comment by GryzleeVEVO** [comment]
Siento haber tardado

Como veas, con tal de que haya instrucciones claras (por ahora se puede poner en el readme).
